-- Reference: LunarVim/Neovim-from-scratch

require "user.basic"
require "user.option"
require "user.keymap"
require "user.plugin"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.lualine"
require "user.autopairs"

require "user.nvim-tree"
require "user.indentline"
require "user.alpha"
require "user.bufferline"
require "user.gitsigns"
require "user.impatient"
require "user.toggleterm"
require "user.neoscroll"
require "user.oscyank"
require "user.linediff"
require "user.doge"
require "user.headlines"
require "user.wilder"
require "user.easy-align"
require "user.hlslens"
require "user.exchange"
require "user.which-key"
require "user.autocmd"
